name: tournament_app
description: A simple tournament app demo (registration, create/join, mock payments)
version: 1.0.0+1
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # Uncomment to integrate Razorpay:
  # razorpay_flutter: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
